//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogMVC.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Fixedrule : Rules
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int RuleId { get; set; }

        [Required]
        [MaxLength(50)]
        public string Query { get; set; }

        [Required]
        [MaxLength(50)]
        public string Response { get; set; }
        public string Createdby { get; set; }
        public string LastUpdatedby { get; set; }
        public string Status { get; set; }
        public string UserId { get; set; }
        public string Type { get; set; }
    }
}
