//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogMVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemRule
    {
        public int RuleId { get; set; }
        public string Query { get; set; }
        public string Response { get; set; }
        public string RuleType { get; set; }
    }
}
