//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogMVC.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TopicInformation
    {
        [Key]
        [Required]
        public int WeekNumber { get; set; }
        [Required]
        public string Topic { get; set; }
        public string LastUpdatedBy { get; set; }
    }
}
