//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogMVC.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UTSDatabaseEntities : DbContext
    {
        public UTSDatabaseEntities()
            : base("name=UTSDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DyanamicRule> DyanamicRules { get; set; }
        public virtual DbSet<Fixedrule> Fixedrules { get; set; }
        public virtual DbSet<TopicInformation> TopicInfo { get; set; }
        public virtual DbSet<SystemRule> SystemRules { get; set; }
    }
}
